name: flutter_inappwebview_example
description: Demonstrates how to use the flutter_inappwebview plugin.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_downloader: ^1.12.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  pointer_interceptor: ^0.10.1+2
  shared_preferences: ^2.5.4
  provider: ^6.1.5
  intl: ^0.18.1
  file_picker: ^10.3.8
  flutter_inappwebview:
    path: ../

dependency_overrides:
  flutter_inappwebview_platform_interface:
    path: ../../flutter_inappwebview_platform_interface
  flutter_inappwebview_android:
    path: ../../flutter_inappwebview_android
  flutter_inappwebview_ios:
    path: ../../flutter_inappwebview_ios
  flutter_inappwebview_macos:
    path: ../../flutter_inappwebview_macos
  flutter_inappwebview_web:
    path: ../../flutter_inappwebview_web
  flutter_inappwebview_windows:
    path: ../../flutter_inappwebview_windows
  flutter_inappwebview_linux:
    path: ../../flutter_inappwebview_linux

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/js/
    - assets/css/
    - assets/images/
    - assets/website/
    - test_assets/
    - test_assets/js/
    - test_assets/css/
    - test_assets/images/
    - test_assets/website/
